### ISSUE TITLE
Predeploying custom contracts that do not have a constructor fails with SEGV runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by sebastiendan** [0xPolygon/polygon-edge#1088]
# Predeploying custom contracts that do not have a constructor fails with SEGV
## Description
Polygon Edge's documentation details [here](https://wiki.polygon.technology/docs/edge/additional-features/predeployment#how-do-i-predeploy-a-smart-contract) how to predeploy an example contract via the `polygon-edge genesis predeploy` CLI command. 

Using the same example contract except with its constructor commented—**or any contract that doesn't have a constructor**—leads to a failed predeploy command execution with a SEGV error. See the full error below:

```
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1560afc]

goroutine 1 [running]:
github.com/0xPolygon/polygon-edge/command.(*CLIOutput).getCommandOutput(...)
        /polygon-edge/command/cli_output.go:31
github.com/0xPolygon/polygon-edge/command.(*CLIOutput).WriteOutput(0xc000010910?)
        /polygon-edge/command/cli_output.go:23 +0x7c
panic({0x175b040, 0x2e3aec0})
        /usr/local/go/src/runtime/panic.go:838 +0x207
github.com/0xPolygon/polygon-edge/helper/predeployment.GenerateGenesisAccountFromFile({0x7ffd22acff14?, 0x40f5e7?}, {0x31074b0, 0x0, 0x0}, {0x0, 0x0, 0x0, 0x0, 0x0, ...})
        /polygon-edge/helper/predeployment/predeployment.go:196 +0x110
github.com/0xPolygon/polygon-edge/command/genesis/predeploy.(*predeployParams).updateGenesisConfig(0x30d2dc0)
        /polygon-edge/command/genesis/predeploy/params.go:136 +0x8b
github.com/0xPolygon/polygon-edge/command/genesis/predeploy.runCommand(0xc00104e300?, {0x19c0266?, 0x6?, 0x6?})
        /polygon-edge/command/genesis/predeploy/genesis_predeploy.go:63 +0x7d
github.com/spf13/cobra.(*Command).execute(0xc00104e300, {0xc000ab0600, 0x6, 0x6})
        /go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc000f15200)
        /go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/0xPolygon/polygon-edge/command/root.(*RootCommand).Execute(0xc0000021a0?)
        /polygon-edge/command/root/root.go:61 +0x1c
main.main()
        /polygon-edge/main.go:18 +0x51
init exited with code 2
```

## Your environment
- MacOS 13.1
- polygon-edge version: "none" (running the `docker/local` docker compose stack from latest `develop`)
- Branch: `develop`
- Running locally
- Running in Docker, with the `docker/local` docker compose stack extended with the predeploy command in `polygon-edge.sh` and the contract json file COPY in Dockerfile

## Steps to reproduce
- Generate new secrets
- Generate a new genesis file
- Take the example contract from [here](https://wiki.polygon.technology/docs/edge/additional-features/predeployment#how-do-i-predeploy-a-smart-contract) and comment its constructor
- Compile the contract and take the json output
- Run `polygon-edge genesis predeploy --chain ./genesis.json --artifacts-path ./Greeter.json --predeploy-address "0x01110"` (no `--constructor-args` arguments)
- Observe the failed command execution
- Restart the whole process but with the example contract's constructor uncommented, with the original `--constructor-args` arguments from the documentation, and observe the successful command execution

## Expected behavior
- The `genesis predeploy` command should return the address of the deployed contract
- Instead, the command fails to execute and return a SEGV error

**Comment by avenbreaks** [comment]
> # Predeploying custom contracts that do not have a constructor fails with SEGV
> ## Description
> Polygon Edge's documentation details [here](https://wiki.polygon.technology/docs/edge/additional-features/predeployment#how-do-i-predeploy-a-smart-contract) how to predeploy an example contract via the `polygon-edge genesis predeploy` CLI command.
> 
> Using the same example contract except with its constructor commented—**or any contract that doesn't have a constructor**—leads to a failed predeploy command execution with a SEGV error. See the full error below:
> 
> ```
> panic: runtime error: invalid memory address or nil pointer dereference
>         panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1560afc]
> 
> goroutine 1 [running]:
> github.com/0xPolygon/polygon-edge/command.(*CLIOutput).getCommandOutput(...)
>         /polygon-edge/command/cli_output.go:31
> github.com/0xPolygon/polygon-edge/command.(*CLIOutput).WriteOutput(0xc000010910?)
>         /polygon-edge/command/cli_output.go:23 +0x7c
> panic({0x175b040, 0x2e3aec0})
>         /usr/local/go/src/runtime/panic.go:838 +0x207
> github.com/0xPolygon/polygon-edge/helper/predeployment.GenerateGenesisAccountFromFile({0x7ffd22acff14?, 0x40f5e7?}, {0x31074b0, 0x0, 0x0}, {0x0, 0x0, 0x0, 0x0, 0x0, ...})
>         /polygon-edge/helper/predeployment/predeployment.go:196 +0x110
> github.com/0xPolygon/polygon-edge/command/genesis/predeploy.(*predeployParams).updateGenesisConfig(0x30d2dc0)
>         /polygon-edge/command/genesis/predeploy/params.go:136 +0x8b
> github.com/0xPolygon/polygon-edge/command/genesis/predeploy.runCommand(0xc00104e300?, {0x19c0266?, 0x6?, 0x6?})
>         /polygon-edge/command/genesis/predeploy/genesis_predeploy.go:63 +0x7d
> github.com/spf13/cobra.(*Command).execute(0xc00104e300, {0xc000ab0600, 0x6, 0x6})
>         /go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
> github.com/spf13/cobra.(*Command).ExecuteC(0xc000f15200)
>         /go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bc
> github.com/spf13/cobra.(*Command).Execute(...)
>         /go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
> github.com/0xPolygon/polygon-edge/command/root.(*RootCommand).Execute(0xc0000021a0?)
>         /polygon-edge/command/root/root.go:61 +0x1c
> main.main()
>         /polygon-edge/main.go:18 +0x51
> init exited with code 2
> ```
> 
> ## Your environment
> * MacOS 13.1
> * polygon-edge version: "none" (running the `docker/local` docker compose stack from latest `develop`)
> * Branch: `develop`
> * Running locally
> * Running in Docker, with the `docker/local` docker compose stack extended with the predeploy command in `polygon-edge.sh` and the contract json file COPY in Dockerfile
> 
> ## Steps to reproduce
> * Generate new secrets
> * Generate a new genesis file
> * Take the example contract from [here](https://wiki.polygon.technology/docs/edge/additional-features/predeployment#how-do-i-predeploy-a-smart-contract) and comment its constructor
> * Compile the contract and take the json output
> * Run `polygon-edge genesis predeploy --chain ./genesis.json --artifacts-path ./Greeter.json --predeploy-address "0x01110"` (no `--constructor-args` arguments)
> * Observe the failed command execution
> * Restart the whole process but with the example contract's constructor uncommented, with the original `--constructor-args` arguments from the documentation, and observe the successful command execution
> 
> ## Expected behavior
> * The `genesis predeploy` command should return the address of the deployed contract
> * Instead, the command fails to execute and return a SEGV error

same issue, but im solved to downgrade golang to v1.18.1

**Comment by ivanbozic21** [comment]
@sebastiendan, if we understood you correctly the issue was resolved. by downgrading to goland v1.18.1 version?

**Comment by sebastiendan** [comment]
@ivanbozic21 The [Dockerfile](https://github.com/0xPolygon/polygon-edge/blob/develop/docker/local/Dockerfile#L1) in `docker/local` is already using `1.18-alpine`. I've just tested with `1.18.1-alpine` and `1.17-alpine` and that hasn't resolved the issue.

**Comment by ivanbozic21** [comment]
Hi @sebastiendan 
Currently, it's required to define --constructor-args in when using predeploy command.

Can you please tell us in more detail why you have a requirement to run it without out?

**Comment by sebastiendan** [comment]
> Hi @sebastiendan Currently, it's required to define --constructor-args in when using predeploy command.
> 
> Can you please tell us in more detail why you have a requirement to run it without out?

Hi @ivanbozic21, the use case is the one of predeploying a contract that does _not_ have a constructor (a situation where one cannot use `--constructor-args`)

**Comment by ivanbozic21** [comment]
@sebastiendan Apology for the late response, and I will try to provide you with an update today.

**Comment by laviniat1996** [comment]
@sebastiendan I'm very sorry for getting back this late. Are you using hardhat to pre-deploy? Could you please provide the contract and script you are using?

**Comment by ivanbozic21** [comment]
@sebastiendan I'm very sorry for getting back this late. Are you using hardhat to pre-deploy? Could you please provide the contract and script you are using?

**Comment by laviniat1996** [comment]
Closing due to inactivity.

**Comment by sebastiendan** [comment]
Hi, sorry for not replying (I changed my github notification settings in a wrong way).

@laviniat1996 Not sure to understand the question, the issue description contains everything you're asking (I reproduced the problem with Polygon's test contract and with the `polygon-edge genesis predeploy` CLI command).
