### ISSUE TITLE
Contract call made panic: runtime error on node and crushed the nodes

### ISSUE THREAD

**Issue by dorijan** [0xPolygon/polygon-edge#1262]
# Contract call made panic: runtime error on node
## Description
I am running a polygon-edge 0.6.3, have 2 bootnodes, and additional 5 nodes, and I made a contract, called a contract and it made a polygon-edge to crash

## Your environment
- ubuntu 22.04
- The version of the Polygon Edge: 0.6.3
- The branch that causes this issue.
- Locally hosted
- runned as binary (not in docker)

## Steps to reproduce
- I was using this smart contract and called the smart contract, 
`https://testnet.vscscan.org/address/0x36344F76A0FB5c18AE8c9353de7C08B681F21d12/contracts#address-tabs`
- then called this transaction
`https://testnet.vscscan.org/tx/0x60f826a11ac50060698aa7b2a2f39bd155c0d89b2e7fa86a0ec1b4767e00d84e`

## Logs
nodes crashed in a way they did not want to start.
Here is the log

```
2023-03-01T11:31:50.109Z [INFO]  polygon.server.ibft.consensus: we are the proposer
2023-03-01T11:31:50.109Z [INFO]  polygon.server.ibft: executed txs: successful=0 failed=0 skipped=0 remaining=2
panic: runtime error: slice bounds out of range [:128] with capacity 96

goroutine 668 [running]:
github.com/0xPolygon/polygon-edge/state/runtime/evm.opCall.func1(0xc003c44120)
/go/src/state/runtime/evm/instructions.go:1177 +0x909
github.com/0xPolygon/polygon-edge/state/runtime/evm.(*state).Run(0xc003c44120)
/go/src/state/runtime/evm/state.go:262 +0x15e
github.com/0xPolygon/polygon-edge/state/runtime/evm.(*EVM).Run(0x30fa650, 0xc0008106e0, {0x21524a8?, 0xc003637d40}, 0xc003637d70)
        /go/src/state/runtime/evm/evm.go:45 +0x15f
github.com/0xPolygon/polygon-edge/state.(*Transition).run(0xc003637d40, 0xc0008106e0, {0x21524a8, 0xc003637d40})
        /go/src/state/executor.go:530 +0x18a
github.com/0xPolygon/polygon-edge/state.(*Transition).applyCall(0xc003637d40, 0xc0008106e0, 0x0, {0x21524a8, 0xc003637d40})
        /go/src/state/executor.go:585 +0x2d0
github.com/0xPolygon/polygon-edge/state.(*Transition).Call2(0xc003637d40, {0x7f, 0x48, 0x69, 0x24, 0xfb, 0x57, 0x95, 0x2a, 0xa8, ...}, ...)
        /go/src/state/executor.go:520 +0x265
github.com/0xPolygon/polygon-edge/state.(*Transition).apply(0xc003637d40, 0xc003ae6a00)
/go/src/state/executor.go:475 +0x725
github.com/0xPolygon/polygon-edge/state.(*Transition).Apply(0xc003637d40, 0xc0035178b8?)
/go/src/state/executor.go:332 +0x133
github.com/0xPolygon/polygon-edge/state.(*Transition).Write(0xc003637d40, 0xc003b0e1e0)
/go/src/state/executor.go:263 +0x14e
github.com/0xPolygon/polygon-edge/consensus/ibft.(*backendIBFT).writeTransaction(0xc000d8c000, 0xc003b0e1e0, {0x213d820?, 0xc003637d40?}, 0x24d89c1cc?)
        /go/src/consensus/ibft/consensus_backend.go:380 +0x12f
github.com/0xPolygon/polygon-edge/consensus/ibft.(*backendIBFT).writeTransactions(0xc000d8c000, {0x21458f8, 0xc0039fd440}, 0x5560b873b04cc351?, 0x30c02e0?, {0x213d820, 0xc003637d40})
        /go/src/consensus/ibft/consensus_backend.go:325 +0x1f1
github.com/0xPolygon/polygon-edge/consensus/ibft.(*backendIBFT).buildBlock(0xc000d8c000, 0xc0036dfb00)
/go/src/consensus/ibft/consensus_backend.go:206 +0x469
github.com/0xPolygon/polygon-edge/consensus/ibft.(*backendIBFT).BuildProposal(0xc000d8c000, 0x9c1dc)
/go/src/consensus/ibft/consensus_backend.go:33 +0x13a
github.com/0xPolygon/go-ibft/core.(*IBFT).buildProposal(0xc0004c8ab0, {0x2145888?, 0xc003af0980?}, 0x0?)
/go/pkg/mod/github.com/0x!polygon/go-ibft@v0.0.0-20220810095021-e43142f8d267/core/ibft.go:932 +0x9a
github.com/0xPolygon/go-ibft/core.(*IBFT).startRound(0xc0004c8ab0, {0x2145888, 0xc003af0980})
/go/pkg/mod/github.com/0x!polygon/go-ibft@v0.0.0-20220810095021-e43142f8d267/core/ibft.go:372 +0x13a
created by github.com/0xPolygon/go-ibft/core.(*IBFT).RunSequence
/go/pkg/mod/github.com/0x!polygon/go-ibft@v0.0.0-20220810095021-e43142f8d267/core/ibft.go:313 +0x4d0

```

**Comment by begmaroman** [comment]
What function did you call @dorijan?
Also, could you try using polybft instead of ibft?

**Comment by stana-miric** [comment]
The problem occurred because the memory was not allocated as we can see from the log "slice bounds out of range [:128] with capacity 96" and this occurred in opCall  when trying to copy return data to state memory(instructions.go line number 1177 in polygon-edge 0.6.3). This could happen only in case when size is 0, and this problem is fixed in [this PR](https://github.com/0xPolygon/polygon-edge/pull/1180)

**Comment by stana-miric** [comment]
As agreed with @igorcrevar and @dusan-maksimovic , I'm closing this issue
