### ISSUE TITLE
error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by thereisnspoon** [0xPolygon/polygon-edge#2014]
hi, i tried to run palm self node but i get the following error.
```
root@palm-new:~/polygon-edge# ./polygon-edge server --data-dir=/root/polygon-edge/datadir --chain=/root/polygon-edge/datadir/genesis-mainnet.json --libp2p "0.0.0.0:30301" --devp2p "0.0.0.0:30302" --jsonrpc="0.0.0.0:8545" --grpc-address="0.0.0.0:9632"

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x18bb651]

goroutine 1 [running]:
github.com/0xPolygon/polygon-edge/server.NewManager(0xc000dbbf40)
        /root/polygon-edge/server/server_manager.go:57 +0x71
github.com/0xPolygon/polygon-edge/command/server.runServerLoop(0x3703dc0?, {0x28220a0, 0xc000dcc2c0})
        /root/polygon-edge/command/server/server.go:319 +0x27
github.com/0xPolygon/polygon-edge/command/server.runCommand(0xc000d8bb00?, {0x1eb2239?, 0x8?, 0x8?})
        /root/polygon-edge/command/server/server.go:307 +0x45
github.com/spf13/cobra.(*Command).execute(0xc000d8bb00, {0xc000d92480, 0x8, 0x8})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc000004c00)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/0xPolygon/polygon-edge/command/root.(*RootCommand).Execute(0xc000006340?)
        /root/polygon-edge/command/root/root.go:68 +0x1c
main.main()
        /root/polygon-edge/main.go:18 +0x51

```

**Comment by Stefan-Ethernal** [comment]
I believe this is related to the Palm, the fork of Edge (https://github.com/gateway-fm/polygon-edge/tree/palm-migration).

I have looked briefly at the codebase and seems like the genesis configuration is invalid (something is missing there).
Plugging @hexoscott so he can take a look. However, I'm closing this issue, because it has nothing to do with the polygon edge itself (the `server_manager` component, which appears in the stack trace, does not exist in the original Edge codebase, but it belongs to Palm).
