### ISSUE TITLE
Polygon-Edge server shows errors when trying to send transaction using Metamask

### ISSUE THREAD

**Issue by spunkyshooter** [0xPolygon/polygon-edge#443]
### Description
We are trying to create a sidechain to polygon using polygon-edge.

I had installed using `go install github.com/0xPolygon/polygon-edge@develop`

I had setup the blockchain using local setup and connected the network with Metamask.

I am facing problem testing sending transactions.
When ever I open the SEND page on metamask, errors are shown on a validator node terminal which metamask is connected to. Logs attached below.

And I am unable to proceeded further on Metamask, Next button greys out. 
Sometimes, when Next Button shows, the initiated transaction will be in pending state forever.

![image](https://user-images.githubusercontent.com/29997888/157495965-94bcbf4b-4ef7-4f19-ad4a-e77dbfcf4584.png)
![image](https://user-images.githubusercontent.com/29997888/157503170-d1410d3b-119f-401f-8232-ccb478383760.png)

`genesis.json`

```
{
    "name": "spring",
    "genesis": {
        "nonce": "0x0000000000000000",
        "timestamp": "0x0",
        "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000c3c080c0",
        "gasLimit": "0x500000",
        "difficulty": "0x1",
        "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "coinbase": "0x0000000000000000000000000000000000000000",
        "alloc": {
            "0xBC726feE350e4aFe042e5a2Ba7A130509EE4F3aC": {
                "balance": "0x3635c9adc5dea00000"
            }
        },
        "number": "0x0",
        "gasUsed": "0x70000",
        "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
    },
    "params": {
        "forks": {
            "homestead": 0,
            "byzantium": 0,
            "constantinople": 0,
            "petersburg": 0,
            "istanbul": 0,
            "EIP150": 0,
            "EIP158": 0,
            "EIP155": 0
        },
        "chainID": 100,
        "engine": {
            "ibft": {
                "epochSize": 100000,
                "type": "PoA"
            }
        },
        "blockGasTarget": 0
    },
    "bootnodes": [
        "/ip4/127.0.0.1/tcp/10001/p2p/16Uiu2HAmKAH3h59BDHAPCGzunEdLnMZswYhfH23PHcYVxFPViBjH",
        "/ip4/127.0.0.1/tcp/20001/p2p/16Uiu2HAm83QUiX4rj8fnm7zaEQUU4sKQcwDHRq6ffoouwPPWHxuf"
    ]
}
```
### Your environment

* OS and version: Windows 10
* version of the Polygon Edge:  v0.1.0
* version of GO: 1.17.8 windows/amd64
* branch that causes this issue: develop

### Steps to reproduce
- Follow the current doc: https://edge-docs.polygon.technology/docs/get-started/set-up-ibft-locally
- Make sure you premine some balance to wallet account
- After running the validator node. connect network with Metamask, use JSONRPC url. 
- Try to send amount to another test account. 

### Expected behaviour
Sending transactions should work

### Actual behaviour
Errors shouldn't occur and sending transactions should work

### Logs
logs: [https://mclo.gs/5Pw7rL4 1](https://mclo.gs/5Pw7rL4) .

```
2022-03-09T00:29:06.540+0530 [INFO]  polygon.network: Peer connected: id=16Uiu2HAm9fsYKLUC1CmHY9eDfreWiAgEJxgAMjSVUsSADyx6EJDF
--
14 | 2022/03/09 00:29:10 http: panic serving 127.0.0.1:49792: runtime error: index out of range [-1]
15 | goroutine 255 [running]:
16 | net/http.(*conn).serve.func1()
17 | C:/Program Files/Go/src/net/http/server.go:1802 +0xb9
18 | panic({0x1125920, 0xc00003ed08})
19 | C:/Program Files/Go/src/runtime/panic.go:1047 +0x266
20 | github.com/0xPolygon/polygon-edge/crypto.RecoverPubkey({0x0, 0x1, 0x16e8ee}, {0xc00053f860, 0x0, 0xc00053f820})
21 | C:/Users/happi/go/pkg/mod/github.com/0x!polygon/polygon-edge@v0.2.2-0.20220304102428-b06e562914d8/crypto/crypto.go:144 +0x135
22 | github.com/0xPolygon/polygon-edge/consensus/ibft.ecrecoverImpl({0x0, 0x0, 0x0}, {0xc00053f820, 0x2d574, 0xa8})
23 | C:/Users/happi/go/pkg/mod/github.com/0x!polygon/polygon-edge@v0.2.2-0.20220304102428-b06e562914d8/consensus/ibft/sign.go:22 +0xa5
24 | github.com/0xPolygon/polygon-edge/consensus/ibft.ecrecoverFromHeader(0x20)
25 | C:/Users/happi/go/pkg/mod/github.com/0x!polygon/polygon-edge@v0.2.2-0.20220304102428-b06e562914d8/consensus/ibft/sign.go:42 +0xc5
26 | github.com/0xPolygon/polygon-edge/consensus/ibft.(*Ibft).GetBlockCreator(0x0, 0x20)
27 | C:/Users/happi/go/pkg/mod/github.com/0x!polygon/polygon-edge@v0.2.2-0.20220304102428-b06e562914d8/consensus/ibft/ibft.go:1268 +0x2e
28 | github.com/0xPolygon/polygon-edge/server.(*jsonRPCHub).ApplyTxn(0xc00183a5f0, 0xc0003d3680, 0x8)
29 | C:/Users/happi/go/pkg/mod/github.com/0x!polygon/polygon-edge@v0.2.2-0.20220304102428-b06e562914d8/server/server.go:467 +0x53
30 | github.com/0xPolygon/polygon-edge/jsonrpc.(*Eth).EstimateGas.func1(0x264ea4)
31 | C:/Users/happi/go/pkg/mod/github.com/0x!polygon/polygon-edge@v0.2.2-0.20220304102428-b06e562914d8/jsonrpc/eth_endpoint.go:561 +0x65
32 | github.com/0xPolygon/polygon-edge/jsonrpc.(*Eth).EstimateGas(0xc001823830, 0xc0022581f0, 0x0)
33 | C:/Users/happi/go/pkg/mod/github.com/0x!polygon/polygon-edge@v0.2.2-0.20220304102428-b06e562914d8/jsonrpc/eth_endpoint.go:574 +0xa4c
34 | reflect.Value.call({0xc00057ae00, 0xc0005787d0, 0x1150c60}, {0x11dd311, 0x4}, {0xc0003a19a0, 0x3, 0xf050c0})
35 | C:/Program Files/Go/src/reflect/value.go:556 +0x845
36 | reflect.Value.Call({0xc00057ae00, 0xc0005787d0, 0xc00223dd88}, {0xc0003a19a0, 0x3, 0x3})
37 | C:/Program Files/Go/src/reflect/value.go:339 +0xc5
38 | github.com/0xPolygon/polygon-edge/jsonrpc.(*Dispatcher).handleReq(0xc00183a640, {{0xf3e780, 0xc00223dd88}, {0xc00223ddd0, 0xf}, {0xc000432580, 0xa2, 0xb0}})
39 | C:/Users/happi/go/pkg/mod/github.com/0x!polygon/polygon-edge@v0.2.2-0.20220304102428-b06e562914d8/jsonrpc/dispatcher.go:296 +0x492
40 | github.com/0xPolygon/polygon-edge/jsonrpc.(*Dispatcher).Handle(0xc0025741e0, {0xc00048a200, 0xeb, 0x200})
41 | C:/Users/happi/go/pkg/mod/github.com/0x!polygon/polygon-edge@v0.2.2-0.20220304102428-b06e562914d8/jsonrpc/dispatcher.go:237 +0x165
42 | github.com/0xPolygon/polygon-edge/jsonrpc.(*JSONRPC).handle(0xc001823d70, {0x1709700, 0xc00156e620}, 0xc000758800)
43 | C:/Users/happi/go/pkg/mod/github.com/0x!polygon/polygon-edge@v0.2.2-0.20220304102428-b06e562914d8/jsonrpc/jsonrpc.go:263 +0x4a4
44 | net/http.HandlerFunc.ServeHTTP(0xc0018e7050, {0x1709700, 0xc00156e620}, 0xc0019639f8)
45 | C:/Program Files/Go/src/net/http/server.go:2047 +0x2f
46 | github.com/0xPolygon/polygon-edge/jsonrpc.middlewareFactory.func1.1({0x1709700, 0xc00156e620}, 0xc000758800)
47 | C:/Users/happi/go/pkg/mod/github.com/0x!polygon/polygon-edge@v0.2.2-0.20220304102428-b06e562914d8/jsonrpc/jsonrpc.go:119 +0xc2
48 | net/http.HandlerFunc.ServeHTTP(0xf9466, {0x1709700, 0xc00156e620}, 0xc00156e620)
49 | C:/Program Files/Go/src/net/http/server.go:2047 +0x2f
50 | net/http.(*ServeMux).ServeHTTP(0x0, {0x1709700, 0xc00156e620}, 0xc000758800)
51 | C:/Program Files/Go/src/net/http/server.go:2425 +0x149
52 | net/http.serverHandler.ServeHTTP({0x1705750}, {0x1709700, 0xc00156e620}, 0xc000758800)
53 | C:/Program Files/Go/src/net/http/server.go:2879 +0x43b
54 | net/http.(*conn).serve(0xc0003a6640, {0x1717e28, 0xc002540b40})
55 | C:/Program Files/Go/src/net/http/server.go:1930 +0xb08
56 | created by net/http.(*Server).Serve
57 | C:/Program Files/Go/src/net/http/server.go:3034 +0x4e8
58 | 2022/03/09 00:29:10 http: panic serving 127.0.0.1:49793: runtime error: index out of range [-1]
59 | goroutine 276 [running]:
```

### Proposed solution

If you have an idea of how to fix this issue, please write it down here, so we can begin discussing it

**Comment by spunkyshooter** [comment]
Update: 
I updated the to latest version v0.3.1, Still has the same issues.


```
D:\projects\SpringBlockchain>polygon-edge server --data-dir ./validator-2 --chain genesis.json --grpc :20000 --libp2p :20001 --jsonrpc :20002 --seal
2022-03-10T00:54:18.425+0530 [INFO]  polygon: Data dir: path=./validator-2
2022-03-10T00:54:18.689+0530 [INFO]  polygon.blockchain: Current header: hash=0x20313ed517e02c22fc48019b0e2278ff39f9d6abfcf3e470c02f43c012520558 number=0
2022-03-10T00:54:18.689+0530 [INFO]  polygon.blockchain: genesis: hash=0x20313ed517e02c22fc48019b0e2278ff39f9d6abfcf3e470c02f43c012520558
2022-03-10T00:54:18.690+0530 [INFO]  polygon.jsonrpc: http server started: addr=0.0.0.0:20002
2022-03-10T00:54:18.691+0530 [INFO]  polygon.consensus.ibft: validator key: addr=0x92a4004394DD78091C7151388467DBC17f416578
2022-03-10T00:54:18.692+0530 [INFO]  polygon.consensus.ibft: state change: new=SyncState
2022-03-10T00:54:18.692+0530 [INFO]  polygon: GRPC server running: addr=127.0.0.1:20000
2022-03-10T00:54:18.692+0530 [INFO]  polygon.network: LibP2P server running: addr=/ip4/127.0.0.1/tcp/20001/p2p/16Uiu2HAm83QUiX4rj8fnm7zaEQUU4sKQcwDHRq6ffoouwPPWHxuf
2022-03-10T00:54:18.692+0530 [INFO]  polygon.network: Omitting bootnode with same ID as host: id=16Uiu2HAm83QUiX4rj8fnm7zaEQUU4sKQcwDHRq6ffoouwPPWHxuf
2022-03-10T00:54:18.708+0530 [INFO]  polygon.network: Peer connected: id=16Uiu2HAmKAH3h59BDHAPCGzunEdLnMZswYhfH23PHcYVxFPViBjH
2022-03-10T00:54:46.633+0530 [INFO]  polygon.network: Peer connected: id=16Uiu2HAmP6bQtmnMwkbGejd6yixZAHYpzgZuHQx7xysTxQBm2mfg
2022-03-10T00:54:54.589+0530 [INFO]  polygon.network: Peer connected: id=16Uiu2HAm9fsYKLUC1CmHY9eDfreWiAgEJxgAMjSVUsSADyx6EJDF
2022/03/10 00:55:14 http: panic serving 127.0.0.1:56918: runtime error: index out of range [-1]
goroutine 171 [running]:
net/http.(*conn).serve.func1()
        C:/Program Files/Go/src/net/http/server.go:1802 +0xb9
panic({0x1d1b100, 0xc0005acf00})
        C:/Program Files/Go/src/runtime/panic.go:1047 +0x266
github.com/0xPolygon/polygon-edge/crypto.RecoverPubkey({0x0, 0x1, 0x1f1f3043665}, {0xc0010d5e20, 0x0, 0xc0010d5de0})
        C:/Users/happi/go/pkg/mod/github.com/0x!polygon/polygon-edge@v0.3.1/crypto/crypto.go:144 +0x135
github.com/0xPolygon/polygon-edge/consensus/ibft.ecrecoverImpl({0x0, 0x0, 0x0}, {0xc0010d5de0, 0xc0d574, 0x0})
        C:/Users/happi/go/pkg/mod/github.com/0x!polygon/polygon-edge@v0.3.1/consensus/ibft/sign.go:22 +0xa5
github.com/0xPolygon/polygon-edge/consensus/ibft.ecrecoverFromHeader(0x20)
        C:/Users/happi/go/pkg/mod/github.com/0x!polygon/polygon-edge@v0.3.1/consensus/ibft/sign.go:42 +0xc5
github.com/0xPolygon/polygon-edge/consensus/ibft.(*Ibft).GetBlockCreator(0x4f, 0x58)
        C:/Users/happi/go/pkg/mod/github.com/0x!polygon/polygon-edge@v0.3.1/consensus/ibft/ibft.go:1268 +0x2e
github.com/0xPolygon/polygon-edge/server.(*jsonRPCHub).ApplyTxn(0xc000071180, 0xc00013bb00, 0xc000061400)
        C:/Users/happi/go/pkg/mod/github.com/0x!polygon/polygon-edge@v0.3.1/server/server.go:467 +0x53
github.com/0xPolygon/polygon-edge/jsonrpc.(*Eth).EstimateGas.func4(0x282904, 0x1)
        C:/Users/happi/go/pkg/mod/github.com/0x!polygon/polygon-edge@v0.3.1/jsonrpc/eth_endpoint.go:596 +0x84
github.com/0xPolygon/polygon-edge/jsonrpc.(*Eth).EstimateGas(0xc00267ac00, 0xc00255c790, 0x0)
        C:/Users/happi/go/pkg/mod/github.com/0x!polygon/polygon-edge@v0.3.1/jsonrpc/eth_endpoint.go:636 +0xb82
reflect.Value.call({0xc0005c2900, 0xc0010d0208, 0x1d461e0}, {0x1dd309d, 0x4}, {0xc002d799f0, 0x3, 0x1af9740})
        C:/Program Files/Go/src/reflect/value.go:556 +0x845
reflect.Value.Call({0xc0005c2900, 0xc0010d0208, 0xc00255c338}, {0xc002d799f0, 0x3, 0x3})
        C:/Program Files/Go/src/reflect/value.go:339 +0xc5
github.com/0xPolygon/polygon-edge/jsonrpc.(*Dispatcher).handleReq(0xc0000711d0, {{0x1b331c0, 0xc00255c338}, {0xc00255c390, 0xf}, {0xc002d14500, 0x94, 0xa0}})
        C:/Users/happi/go/pkg/mod/github.com/0x!polygon/polygon-edge@v0.3.1/jsonrpc/dispatcher.go:296 +0x492
github.com/0xPolygon/polygon-edge/jsonrpc.(*Dispatcher).Handle(0xc003040460, {0xc002d07400, 0xdd, 0x200})
        C:/Users/happi/go/pkg/mod/github.com/0x!polygon/polygon-edge@v0.3.1/jsonrpc/dispatcher.go:237 +0x165
github.com/0xPolygon/polygon-edge/jsonrpc.(*JSONRPC).handle(0xc00267b140, {0x238f620, 0xc000b247e0}, 0xc002d7d100)
        C:/Users/happi/go/pkg/mod/github.com/0x!polygon/polygon-edge@v0.3.1/jsonrpc/jsonrpc.go:271 +0x4a4
net/http.HandlerFunc.ServeHTTP(0x1cc9480, {0x238f620, 0xc000b247e0}, 0x1b)
        C:/Program Files/Go/src/net/http/server.go:2047 +0x2f
github.com/0xPolygon/polygon-edge/jsonrpc.middlewareFactory.func1.1({0x238f620, 0xc000b247e0}, 0xc002d7d100)
        C:/Users/happi/go/pkg/mod/github.com/0x!polygon/polygon-edge@v0.3.1/jsonrpc/jsonrpc.go:127 +0xc2
net/http.HandlerFunc.ServeHTTP(0xcd9466, {0x238f620, 0xc000b247e0}, 0xc000b247e0)
        C:/Program Files/Go/src/net/http/server.go:2047 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0, {0x238f620, 0xc000b247e0}, 0xc002d7d100)
        C:/Program Files/Go/src/net/http/server.go:2425 +0x149
net/http.serverHandler.ServeHTTP({0x238b670}, {0x238f620, 0xc000b247e0}, 0xc002d7d100)
        C:/Program Files/Go/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc0001da460, {0x239dc48, 0xc0011b1680})
        C:/Program Files/Go/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
        C:/Program Files/Go/src/net/http/server.go:3034 +0x4e8
2022/03/10 00:55:14 http: panic serving [::1]:56919: runtime error: index out of range [-1]
```

Other than that,
I see `polygon-edge@v0.3.1` mentioned in logs 
But executing `polygon-edge version` gives ` v0.1.0`

**Comment by 0xAleksaOpacic** [comment]
hi @spunkyshooter 
I am not able to reproduce this issue on my local machine. Which version of MetaMask and browser are you using?

You will always see v0.1.0 when you are working on the develop branch, only release binaries contains a real version. https://github.com/0xPolygon/polygon-edge/releases. Anyways this is not a reason for this issue

**Comment by spunkyshooter** [comment]
ok, understood. I am using Brave Browser. MetaMask Version v10.10.2

**Comment by spunkyshooter** [comment]
I tried with Edge browser, MetaMask Version v10.10.1 version. Still has the same issue

**Comment by 0xAleksaOpacic** [comment]
@spunkyshooter Thank you for info and checking on different browsers.
I am using chrome, but if you tried both with Edge and Brave i do not see what could be the problem.
I am going to continue investigation and will notify you when I think of something.

**Comment by 0xAleksaOpacic** [comment]
@spunkyshooter 
Can you please try it on Chrome, just to make sure that it is not Browser base problem.

**Comment by ZeljkoBenovic** [comment]
Thank you @spunkyshooter for raising this issue.

What I can tell from the logs, is that the server is crashing during boot.
It doesn't reach the stage where the chain is running and the blocks are generated.
There has to be some mistake during the configuration and server setup process.

Try cloning the develop branch, building a binary from that and running the server.
The process should look something like this:
```
git clone https://github.com/0xPolygon/polygon-edge.git
cd polygon-edge
go build -o artifacts/polygon-edge .
```
copy the polygon-edge binary ( exe file ) from the artifacts folder to the folder that is set in Environment path ( like C:\Windows\System32 ) or run the polygon-edge from artifact folder.

DISCLAMER: The polygon-edge has never been tested on Windows OS. There might be some issue with the Windows OS itself.
Try running some Linux VM like Ubuntu, on a VirtualBox for example, and check if it runs properly there.

The log output for a chain that is running correctly shows something like this:
```
2022-03-09T20:08:35.017Z [INFO]  polygon.blockchain: write block: num=859926 parent=0xf810dee0954f791e8f981935781e4f646e1a5cfba76ebd2dd90846fe782bef3c
2022-03-09T20:08:35.019Z [INFO]  polygon.blockchain: new block: number=859926 hash=0x3997465863c21d29c3d408c73a698f06d6ec64fb32587d179aa19b11726d1a93 txns=0 generation_time_in_seconds=2
2022-03-09T20:08:35.020Z [INFO]  polygon.consensus.ibft: block committed: sequence=859926 hash=0x3997465863c21d29c3d408c73a698f06d6ec64fb32587d179aa19b11726d1a93 validators=6 rounds=1 committed=3
2022-03-09T20:08:35.025Z [INFO]  polygon.consensus.ibft: state change: new=AcceptState
2022-03-09T20:08:35.026Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=859927 round=1
2022-03-09T20:08:35.026Z [INFO]  polygon.consensus.ibft: current snapshot: validators=6 votes=0
2022-03-09T20:08:35.026Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x7fDe0dD72168041DbeAb2202671c1650084b5bf7 block=859927
2022-03-09T20:08:37.007Z [INFO]  polygon.consensus.ibft: state change: new=ValidateState
2022-03-09T20:08:37.016Z [INFO]  polygon.consensus.ibft: state change: new=CommitState
2022-03-09T20:08:37.016Z [INFO]  polygon.blockchain: write block: num=859927 parent=0x3997465863c21d29c3d408c73a698f06d6ec64fb32587d179aa19b11726d1a93
2022-03-09T20:08:37.019Z [INFO]  polygon.blockchain: new block: number=859927 hash=0xfb28bf30038a80a0129aa71a47afa7655e4d10eb3aeebd5ae895a7d33348a039 txns=0 generation_time_in_seconds=2
2022-03-09T20:08:37.019Z [INFO]  polygon.consensus.ibft: block committed: sequence=859927 hash=0xfb28bf30038a80a0129aa71a47afa7655e4d10eb3aeebd5ae895a7d33348a039 validators=6 rounds=1 committed=3
2022-03-09T20:08:37.026Z [INFO]  polygon.consensus.ibft: state change: new=AcceptState
2022-03-09T20:08:37.026Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=859928 round=1
2022-03-09T20:08:37.026Z [INFO]  polygon.consensus.ibft: current snapshot: validators=6 votes=0
2022-03-09T20:08:37.027Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0xfFE587dec46f2AC7B8BBF4a050363e191D5fBe9A block=859928
2022-03-09T20:08:39.007Z [INFO]  polygon.consensus.ibft: state change: new=ValidateState
2022-03-09T20:08:39.016Z [INFO]  polygon.consensus.ibft: state change: new=CommitState
2022-03-09T20:08:39.016Z [INFO]  polygon.blockchain: write block: num=859928 parent=0xfb28bf30038a80a0129aa71a47afa7655e4d10eb3aeebd5ae895a7d33348a039
2022-03-09T20:08:39.018Z [INFO]  polygon.blockchain: new block: number=859928 hash=0x463154440257eda509c398ca316989ceba3552fc13d6da896591c0b0c1801983 txns=0 generation_time_in_seconds=2
2022-03-09T20:08:39.019Z [INFO]  polygon.consensus.ibft: block committed: sequence=859928 hash=0x463154440257eda509c398ca316989ceba3552fc13d6da896591c0b0c1801983 validators=6 rounds=1 committed=3
2022-03-09T20:08:39.025Z [INFO]  polygon.consensus.ibft: state change: new=AcceptState
2022-03-09T20:08:39.025Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=859929 round=1
2022-03-09T20:08:39.026Z [INFO]  polygon.consensus.ibft: current snapshot: validators=6 votes=0
2022-03-09T20:08:39.026Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x5E1964EA2210D637C72986b7af5c8b5E57d0d20B block=859929
2022-03-09T20:08:41.008Z [INFO]  polygon.consensus.ibft: state change: new=ValidateState
2022-03-09T20:08:41.017Z [INFO]  polygon.consensus.ibft: state change: new=CommitState
2022-03-09T20:08:41.017Z [INFO]  polygon.blockchain: write block: num=859929 parent=0x463154440257eda509c398ca316989ceba3552fc13d6da896591c0b0c1801983
2022-03-09T20:08:41.020Z [INFO]  polygon.blockchain: new block: number=859929 hash=0x869e19d71662343c943d7cfcbd3069219011fa3d0babbacfaaf889d8d502034b txns=0 generation_time_in_seconds=2
2022-03-09T20:08:41.020Z [INFO]  polygon.consensus.ibft: block committed: sequence=859929 hash=0x869e19d71662343c943d7cfcbd3069219011fa3d0babbacfaaf889d8d502034b validators=6 rounds=1 committed=3
2022-03-09T20:08:41.028Z [INFO]  polygon.consensus.ibft: state change: new=AcceptState
2022-03-09T20:08:41.028Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=859930 round=1
2022-03-09T20:08:41.028Z [INFO]  polygon.consensus.ibft: current snapshot: validators=6 votes=0
2022-03-09T20:08:41.029Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x83b6A19650B7A399fcC224128CF8b420E93b6A8b block=859930
2022-03-09T20:08:43.006Z [INFO]  polygon.consensus.ibft: state change: new=ValidateState
2022-03-09T20:08:43.015Z [INFO]  polygon.consensus.ibft: state change: new=CommitState
2022-03-09T20:08:43.015Z [INFO]  polygon.blockchain: write block: num=859930 parent=0x869e19d71662343c943d7cfcbd3069219011fa3d0babbacfaaf889d8d502034b
2022-03-09T20:08:43.017Z [INFO]  polygon.blockchain: new block: number=859930 hash=0x073dfed0edca07208b70e8192089e571294118c9c1700e70dc453aaf7418e942 txns=0 generation_time_in_seconds=2
2022-03-09T20:08:43.018Z [INFO]  polygon.consensus.ibft: block committed: sequence=859930 hash=0x073dfed0edca07208b70e8192089e571294118c9c1700e70dc453aaf7418e942 validators=6 rounds=1 committed=3
2022-03-09T20:08:43.025Z [INFO]  polygon.consensus.ibft: state change: new=AcceptState
2022-03-09T20:08:43.026Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=859931 round=1
2022-03-09T20:08:43.026Z [INFO]  polygon.consensus.ibft: current snapshot: validators=6 votes=0
2022-03-09T20:08:43.026Z [INFO]  polygon.consensus.ibft.acceptState: we are the proposer: block=859931
2022-03-09T20:08:43.026Z [INFO]  polygon.consensus.ibft: executed txns: failed =0 successful=0 remaining in pool=0
2022-03-09T20:08:43.027Z [INFO]  polygon.consensus.ibft: build block: number=859931 txns=0
2022-03-09T20:08:45.009Z [INFO]  polygon.consensus.ibft: state change: new=ValidateState
2022-03-09T20:08:45.024Z [INFO]  polygon.consensus.ibft: state change: new=CommitState
2022-03-09T20:08:45.024Z [INFO]  polygon.blockchain: write block: num=859931 parent=0x073dfed0edca07208b70e8192089e571294118c9c1700e70dc453aaf7418e942
2022-03-09T20:08:45.027Z [INFO]  polygon.blockchain: new block: number=859931 hash=0xb6e71a3c9c8b0c5ca48b1f5e918f0d6d1adbb824279b95bcc4d5a9bbe180f6c8 txns=0 generation_time_in_seconds=2
2022-03-09T20:08:45.027Z [INFO]  polygon.consensus.ibft: block committed: sequence=859931 hash=0xb6e71a3c9c8b0c5ca48b1f5e918f0d6d1adbb824279b95bcc4d5a9bbe180f6c8 validators=6 rounds=1 committed=3
2022-03-09T20:08:45.040Z [INFO]  polygon.consensus.ibft: state change: new=AcceptState
2022-03-09T20:08:45.040Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=859932 round=1
2022-03-09T20:08:45.040Z [INFO]  polygon.consensus.ibft: current snapshot: validators=6 votes=0
2022-03-09T20:08:45.041Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0xA37034D86606aB038A6f79a2aABFe75680F37bC6 block=859932
2022-03-09T20:08:47.008Z [INFO]  polygon.consensus.ibft: state change: new=ValidateState
2022-03-09T20:08:47.017Z [INFO]  polygon.consensus.ibft: state change: new=CommitState
```

**Comment by spunkyshooter** [comment]
> @spunkyshooter
Can you please try it on Chrome, just to make sure that it is not Browser base problem.

Tested on Chrome, had same issues. 
![image](https://user-images.githubusercontent.com/29997888/157526157-707389a7-478b-47ef-9669-da167312492c.png)

**Comment by spunkyshooter** [comment]
Thanks @ZeljkoBenovic for the info on windows. I will verify on linux as well. 

Just for the record, these are the logs I get when server is run on windows without Metamask's intervention.

```
D:\projects\SpringBlockchain>polygon-edge server --data-dir ./validator-1 --chain genesis.json --grpc :10000 --libp2p :10001 --jsonrpc :10002 --seal
2022-03-10T01:43:11.839+0530 [INFO]  polygon: Data dir: path=./validator-1
2022-03-10T01:43:12.096+0530 [INFO]  polygon.blockchain: Current header: hash=0x20313ed517e02c22fc48019b0e2278ff39f9d6abfcf3e470c02f43c012520558 number=0
2022-03-10T01:43:12.096+0530 [INFO]  polygon.blockchain: genesis: hash=0x20313ed517e02c22fc48019b0e2278ff39f9d6abfcf3e470c02f43c012520558
2022-03-10T01:43:12.097+0530 [INFO]  polygon.jsonrpc: http server started: addr=0.0.0.0:10002
2022-03-10T01:43:12.099+0530 [INFO]  polygon.consensus.ibft: validator key: addr=0x9895Ff16877B1462Dc1b78375a5b344430F5C029
2022-03-10T01:43:12.099+0530 [INFO]  polygon.consensus.ibft: state change: new=SyncState
2022-03-10T01:43:12.099+0530 [INFO]  polygon: GRPC server running: addr=127.0.0.1:10000
2022-03-10T01:43:12.100+0530 [INFO]  polygon.network: LibP2P server running: addr=/ip4/127.0.0.1/tcp/10001/p2p/16Uiu2HAmKAH3h59BDHAPCGzunEdLnMZswYhfH23PHcYVxFPViBjH
2022-03-10T01:43:12.100+0530 [INFO]  polygon.network: Omitting bootnode with same ID as host: id=16Uiu2HAmKAH3h59BDHAPCGzunEdLnMZswYhfH23PHcYVxFPViBjH
2022-03-10T01:43:12.111+0530 [INFO]  polygon.network: Peer connected: id=16Uiu2HAm83QUiX4rj8fnm7zaEQUU4sKQcwDHRq6ffoouwPPWHxuf
2022-03-10T01:43:16.669+0530 [INFO]  polygon.network: Peer connected: id=16Uiu2HAmP6bQtmnMwkbGejd6yixZAHYpzgZuHQx7xysTxQBm2mfg
2022-03-10T01:43:17.114+0530 [INFO]  polygon.network: Peer connected: id=16Uiu2HAm9fsYKLUC1CmHY9eDfreWiAgEJxgAMjSVUsSADyx6EJDF
```

**Comment by ZeljkoBenovic** [comment]
There should be much more logs.
The default block time is 2s, so basically every 2 seconds the block should be generated and you should see running logs and these logs seams stuck.

Check your config again.
You can try turning on the debug mode as well with ```--log-level DEBUG``` and you should see a lot of running logs.

**Comment by 0xAleksaOpacic** [comment]
hi @spunkyshooter 
I was able to reproduce your issue on my local machine. The way how I was able to reproduce this issue is if I mistype --data-dir path when starting the node. 
Can you please check if the name and path when you have created the secrets match the one you used when starting the node (from the logs I see that you have used --data-dir ./validator-2)

**Comment by spunkyshooter** [comment]
@Aleksao998 
Commands I had used:

To  create Secret:
`polygon-edge secrets init --data-dir validator-2`

To start server:
`polygon-edge server --data-dir ./validator-2 --chain genesis.json --grpc :20000 --libp2p :20001 --jsonrpc :20002 --seal`

I don't see any issues with the data-dir.

This is my folder structure
![image](https://user-images.githubusercontent.com/29997888/157713520-f60eb599-e080-43de-af04-bd2c9f4d175e.png)

**Comment by spunkyshooter** [comment]
@ZeljkoBenovic 

I tried in linux environment, sadly I see the issue there as well. 

Ubuntu: 20.04.3 LTS

Logs: https://mclo.gs/W3a5spr


Here are complete set of commands I used. 

- `go install github.com/0xPolygon/polygon-edge@develop`

Generate Secrets for validators:
- `polygon-edge secrets init --data-dir validator-1`
- `polygon-edge secrets init --data-dir validator-2`
- `polygon-edge secrets init --data-dir validator-3`
- `polygon-edge secrets init --data-dir validator-4`

Create Genesis File:
- using validator-1 and validator-2 as bootnodes. 
- `polygon-edge genesis --consensus ibft --ibft-validators-prefix-path test-chain- --bootnode /ip4/127.0.0.1/tcp/10001/p2p/16Uiu2HAmP9SBYX6JrA6SJ76SDFfqdKCpCGnWgwKJhKzemaX6zDKv --bootnode /ip4/127.0.0.1/tcp/20001/p2p/16Uiu2HAm47Pfz5hCgt4PEi2sdoWX31BU1gGtVuurCt9D3ALhiQor --premine=0xBC726feE350e4aFe042e5a2Ba7A130509EE4F3aC:1000000000000000000000 --name=springrole`

Run Validators:
- ` polygon-edge server --data-dir ./validator-1 --chain genesis.json --grpc :10000 --libp2p :10001 --jsonrpc :10002 --seal`
- `polygon-edge server --data-dir ./validator-2 --chain genesis.json --grpc :20000 --libp2p :20001 --jsonrpc :20002 --seal`
- `polygon-edge server --data-dir ./validator-3 --chain genesis.json --grpc :30000 --libp2p :30001 --jsonrpc :30002 --seal`
- `polygon-edge server --data-dir ./validator-4 --chain genesis.json --grpc :40000 --libp2p :40001 --jsonrpc :40002 --seal`


Used url http://localhost:20002 for registering network on Metamask

**Comment by spunkyshooter** [comment]
I found out the issue. `--ibft-validators-prefix-path test-chain-` was the culprint, 
It should have been `--ibft-validators-prefix-path validator-` for my case. 

Thank you @ZeljkoBenovic and @Aleksao998

**Comment by 0xAleksaOpacic** [comment]
Hi @spunkyshooter 
I am glad that you found the issue. I am going to check the docs and update them if this step seems unclear.
