### ISSUE TITLE
Shutdown sometimes wipes `consensus/metadata` file causing `unexpected end of JSON input` on restart

### ISSUE THREAD

**Issue by dankostiuk** [0xPolygon/polygon-edge#824]
### Description

Ever since pulling in v0.6.0 into our testnet, we sometimes see our nodes get stuck in a restart loop due to `unexpected end of JSON input` errors while reading from an empty `metadata` file. This could be related to the panic shown in the logs below when stopping our service. It looks like the `metadata` file doesn't get a chance to be saved with the latest block prior to shutdown when the panic occurs.

### Your environment

* OS and version `Ubuntu 20`
* version of the Polygon Edge `0.6.0`

### Steps to reproduce

1. Configure `server` to run as a systemd service
2. Call systemctl restart on the service and observe that this error sometimes comes up
3. The only way to resolve is to copy the json from another validator (e.g. `{"LastBlock":10282855}`) -- after that, the node can restart again without issues.

### Expected behaviour

`metadata` should properly be saved, allowing for a normal restart.

### Actual behaviour

`metadata` gets saved as a blank file, preventing the server from running upon restart.

### Logs

```
2022-10-21T04:15:04.819-04:00
{"message":"unexpected end of JSON input"}
2022-10-21T04:15:04.443-04:00
{"message":"2022-10-21T08:15:04.431Z [INFO] polygon: Data dir: path=/home/ubuntu/sx-node/validator-bkup"}
2022-10-21T04:15:03.617-04:00
{"message":"2022-10-21T08:15:03.168Z [INFO] polygon.blockchain: Current header: hash=0xfc8490a36e08061448a6bd577430eeb91b2b7671f311fa883b3688a192a7b938 number=10302838"}
2022-10-21T04:15:03.617-04:00
{"message":"2022-10-21T08:15:03.168Z [INFO] polygon.blockchain: genesis: hash=0x227b4b2ec9025d87b22dfa58b509030b4fcb62e2c1a644d63db7e4fb985ecb76"}
2022-10-21T04:15:01.867-04:00
{"message":"unexpected end of JSON input"}
2022-10-21T04:15:01.117-04:00
{"message":"2022-10-21T08:15:00.674Z [INFO] polygon: Data dir: path=/home/ubuntu/sx-node/validator-bkup"}
2022-10-21T04:15:01.117-04:00
{"message":"2022-10-21T08:15:00.689Z [INFO] polygon: Prometheus server started: addr==0.0.0.0:9000"}
2022-10-21T04:06:33.118-04:00
{"message":"2022-10-21T08:06:32.956Z [INFO] polygon.network: Peer disconnected: id=16Uiu2HAm7xWnL3VLaFwqFzeqcfjkFZRny3WDjiEfjsDzALghrEi4"}
2022-10-21T04:06:33.118-04:00
{"message":"2022-10-21T08:06:32.956Z [INFO] polygon.network: Peer disconnected: id=16Uiu2HAmVWJ7TDHtyoJtSXuDgS8mKvUwWWxzxjTsTTFRU31D6xNA"}
2022-10-21T04:06:33.118-04:00
{"message":"2022-10-21T08:06:32.956Z [INFO] polygon.network: Peer disconnected: id=16Uiu2HAm8fbLe2utrGKrBZ3mArgQRAyuAZXY9C6FV3tL3UtnEVBw"}
2022-10-21T04:06:33.118-04:00
{"message":"2022-10-21T08:06:32.956Z [INFO] polygon.network: Peer disconnected: id=16Uiu2HAmVMCHTqD6Xe1KescA6yt8raf13TAgxiWYKRQV3k1jZR7z"}
2022-10-21T04:06:33.118-04:00
{"message":"2022-10-21T08:06:32.956Z [INFO] polygon.network: Peer disconnected: id=16Uiu2HAm6yfKYWJncEh8SBtt1ptsavc4M1fySpc8ZKDm8wE9hp3x"}
2022-10-21T04:06:33.118-04:00
{"message":"panic: send on closed channel"}
2022-10-21T04:06:33.118-04:00
{"message":"goroutine 143 [running]:"}
2022-10-21T04:06:33.118-04:00
{"message":"github.com/0xPolygon/polygon-edge/syncer.(*syncPeerClient).startPeerEventProcess(0xc0001d8770)"}
2022-10-21T04:06:33.118-04:00
{"message":"\t/home/ubuntu/sx-node/syncer/client.go:232 +0x12a"}
2022-10-21T04:06:33.118-04:00
{"message":"created by github.com/0xPolygon/polygon-edge/syncer.(*syncPeerClient).Start"}
2022-10-21T04:06:33.118-04:00
{"message":"\t/home/ubuntu/sx-node/syncer/client.go:60 +0xa5"}
2022-10-21T04:06:33.107-04:00
{"message":"2022-10-21T08:06:32.833Z [INFO] polygon.blockchain: new block: number=10302838 txs=0 hash=0xfc8490a36e08061448a6bd577430eeb91b2b7671f311fa883b3688a192a7b938 parent=0xe5356d85c67307dcc1b0d93413dac0e3cf5ed536cfe7d80843e97fc236df9bd1 generation_time_in_seconds=2"}
2022-10-21T04:06:33.107-04:00
{"message":"2022-10-21T08:06:32.929Z [DEBUG] polygon.jsonrpc: handle: request=\"{\\\"method\\\":\\\"eth_getBlockByNumber\\\",\\\"params\\\":[\\\"latest\\\"],\\\"id\\\":1,\\\"jsonrpc\\\":\\\"2.0\\\"}\""}
2022-10-21T04:06:33.107-04:00
{"message":"2022-10-21T08:06:32.929Z [DEBUG] polygon.dispatcher: request: method=eth_getBlockByNumber id=1"}
2022-10-21T04:06:33.107-04:00
{"message":"2022-10-21T08:06:32.929Z [DEBUG] polygon.jsonrpc: handle: response=\"{\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":1,\\\"result\\\":{\\\"parentHash\\\":\\\"0xe5356d85c67307dcc1b0d93413dac0e3cf5ed536cfe7d80843e97fc236df9bd1\\\",\\\"sha3Uncles\\\":\\\"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347\\\",\\\"miner\\\":\\\"0x0000000000000000000000000000000000000000\\\",\\\"stateRoot\\\":\\\"0x5a789d3b605a4dcfebd03c922c4c2b8324118341f382c6561eec3992991b772c\\\",\\\"transactionsRoot\\\":\\\"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421\\\",\\\"receiptsRoot\\\":\\\"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421\\\",\\\"logsBloom\\\":\\\"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\\\",\\\"difficulty\\\":\\\"0x9d3576\\\",\\\"totalDifficulty\\\":\\\"0x9d3576\\\",\\\"size\\\":\\\"0x457\\\",\\\"number\\\":\\\"0x9d3576\\\",\\\"gasLimit\\\":\\\"0x3938700\\\",\\\"gasUsed\\\":\\\"0x0\\\",\\\"timestamp\\\":\\\"0x63525306\\\",\\\"extraData\\\":\\\"0x0000000000000000000000000000000000000000000000000000000000000000f9022ff85494a3a585c6d59cce6aae7035e8df48b3327cc8be54947eff16a34e3433182d636488bc97919b10283f37949cde4f11ea57163023a9a8a5df499b27813639eb943e64f88c6c7a1310236b242180c0ba1409d10f4db8417c972793c5fd07a11076cd5c12cbc3ed4d215e57d7d1f8d2e7bf3309380777e408d52531bc147bc835d4b9d35c663250a55e7336afd4731bf34a06af1b1e244c01f8c9b841f36360ee85bfe94f26274e67354d6f713f3abe2ce24b629e77925f6e252880f753310dfa286ebee16c0baed6a4055b6b8ba262e93f3cf7e7fb9e2a3e68dac29b00b841811f3ddddd870edd81062fed889bf9c49d1342c683e55a66272cf2b932038379177c3232e7199bff9bad050b9951b37e5e960aa98898e3521c5382cd0986b72101b841d064c0a95009ef51008aa16632ba7e81eb27e069fafe60a109405c316dcb064479ee8377151e43b0a218b729cec87c8ade30999c6088fccb960649ac2d99a31800f8c9b8410e3e53a47df4fcfdbc49faab8da92b70dc2ced2643480fdd83a913c1e8d416494d2441e3e04e349084bf4f42ee1757e376cd2c3654a3eabfbc92710199b4ef4700b8414c68396470f7556632258d69305e4c04b4af94ff5f7f5b27a00c773ca5ec9acc4fa0033af49b30f17579684a7810e721a52a838fd2c2bb985c8fce1a770fb68600b841408e70ed9f49cfade0efd88d08d243eac5297243b1ec102094c7f61eb76c17a11bd02db426081b6ca617ac7cef5f91f529b28fb88ae08c61a9a6cb22e0472bcb00\\\",\\\"mixHash\\\":\\\"0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365\\\",\\\"nonce\\\":\\\"0x0000000000000000\\\",\\\"hash\\\":\\\"0xfc8490a36e08061448a6bd577430eeb91b2b7671f311fa883b3688a192a7b938\\\",\\\"transactions\\\":[],\\\"uncles\\\":[]}}\""}
2022-10-21T04:06:33.107-04:00
{"message":"[SIGNAL] Caught signal: terminated"}
2022-10-21T04:06:33.107-04:00
{"message":"Gracefully shutting down client..."}
```

**Comment by ivanbozic21** [comment]
Hi @dankostiuk

Please provide us with complete debug logs.

Awaiting your earliest response.

**Comment by ivanbozic21** [comment]
@dankostiuk 
Did you configure this service as per our public documentation? 
Also, can you provide how did you define the config file and a simple explanation about what metadata is?"

**Comment by ivanbozic21** [comment]
@dankostiuk
Did you configure this service as per our public documentation?
Also, can you provide how did you define the config file and a simple explanation about what metadata is?"

**Comment by dankostiuk** [comment]
Yes this service was configured following your documentation and we've only seen issues occasionally on the latest release.

Our config.yml:
```
chain_config: /home/ubuntu/sx-node/validator-2/genesis.json
secrets_config: /home/ubuntu/sx-node/secretsManagerConfig.json
data_dir: /home/ubuntu/sx-node/validator-2
block_gas_target: 0x3938700
grpc_addr: 0.0.0.0:10000
jsonrpc_addr: 0.0.0.0:10002
telemetry:
  prometheus_addr: 0.0.0.0:9000
network:
  libp2p_addr: 0.0.0.0:10001
  dns_addr: dns/validator-2.toronto.sx.technology
seal: true
log_level: DEBUG
```  

By metadata i mean the file written to `consensus/metadata` which keeps track of the last block:
```
{"LastBlock":10283596}
```

**Comment by laviniat1996** [comment]
@dankostiuk We believe [this PR](https://github.com/0xPolygon/polygon-edge/pull/839) fixes this issue. It will be included in the following release.

**Comment by dankostiuk** [comment]
Hey @laviniat1996 , just as an update - we pulled in those changes into our testnet and mainnet but still seem to encounter this issue every so often. Upon restarting our service we encounter a blank `consensus/metatada` file about 20% of the time and have to manually fill it in and restart in order for the validator to continue working properly.

**Comment by dankostiuk** [comment]
@laviniat1996 to follow up with this again, it appears that sometimes on shutdown, the following panic still occurs, even after pulling in @Kourin1996 's changes.

When this panic occurs, the `consensus/metadata` is blank and the service can not restart again. This issue is occurring on both our test environments as well as our production environment.

Additional logging:

```
{"message":"panic: send on closed channel"}
{"message":"goroutine 136 [running]:"}
{"message":"github.com/0xPolygon/polygon-edge/syncer.(*syncPeerClient).startPeerEventProcess(0xc0002e6cb0)"}
{"message":"\t/home/ubuntu/sx-node/syncer/client.go:232 +0x145"}
{"message":"created by github.com/0xPolygon/polygon-edge/syncer.(*syncPeerClient).Start"}
{"message":"\t/home/ubuntu/sx-node/syncer/client.go:60 +0xa5"}
{"message":"[SIGNAL] Caught signal: terminated"}
{"message":"Gracefully shutting down client..."}
```

**Comment by ivanbozic21** [comment]
@dankostiuk our team is still looking into it and we will keep you updated.

**Comment by dankostiuk** [comment]
@ivanbozic21 

This is somewhat of a hack solution but by making this change within `NewSnapshotValidatorStoreWrapper`, this restart loop can be avoided..  With this fix I still see the error message in our logs but now whenever `consensus/metadata` file is blank on startup, we just use the latest snapshot blockNumber as the metadata LastBlock.

It's strange that the `snapshots` file has so far never failed to be written to on Close()..

```
	snapshots, err := loadSnapshots(filepath.Join(dirPath, snapshotSnapshotsFilename))
	if err != nil {
		return nil, err
	}
	
	snapshotMeta, err := loadSnapshotMetadata(filepath.Join(dirPath, snapshotMetadataFilename))
	if err != nil {
		logger.Error("got error loading snapshot metadata", "err", err)
		snapshotMeta = &snapshot.SnapshotMetadata{LastBlock: snapshots[len(snapshots)-1].Number}
	}
```

Would very much appreciate any updates on your team's progress in fixing this. Thanks!

**Comment by ivanbozic21** [comment]
@dankostiuk Thank you for your suggestion, I've passed it to our protocol engineering team for further reviewal.

Please know that we will continue to keep you posted about this request.

**Comment by ivanbozic21** [comment]
@dankostiuk 
Please know that we still don't have any news about your suggestion, and I will continue to keep you updated about this request.

**Comment by laviniat1996** [comment]
@dankostiuk Just wanted to let you know that we were able to reproduce this, and Yoshiki made a fix for it, which is linked to this issue 🙏

**Comment by laviniat1996** [comment]
@dankostiuk The PR which fixed this was merged.
