### ISSUE TITLE
Panic: Send On Closed Channel - Docker On Cloud

### ISSUE THREAD

**Issue by amandatsalis** [0xPolygon/polygon-edge#886]
## Description
RPC Always Down And Pending Production Block

```
[SIGNAL] Caught signal: terminated
Gracefully shutting down client...

panic: send on closed channel

goroutine 133 [running]:
github.com/0xPolygon/polygon-edge/network.(*Server).SubscribeCh.func1(0xc000ee3fb0)
        /polygon-edge/network/server.go:738 +0x36
github.com/0xPolygon/polygon-edge/network.(*Server).SubscribeFn.func1()
        /polygon-edge/network/server.go:717 +0x44
created by github.com/0xPolygon/polygon-edge/network.(*Server).SubscribeFn
        /polygon-edge/network/server.go:713 +0xaf
```

## Your environment
- OS and version. : `Ubuntu 4.15.0-194-generic #205-Ubuntu SMP Fri Sep 16 19:49:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- The version of the Polygon Edge.  : `0.6.0`
- Locally or Cloud hosted (which provider). : `Digital Ocean `
- Please confirm if the validators are running under containerized environment (K8s, Docker, etc.). : `Docker`

## Expected behavior
Running Smooth And Not Down After Running Docker 

## Logs
https://txt.mariomichel.com/?3349726ee8864ef9#EY11S5YQDwUtsjLGbzZTbof9gqMHjf6HEU91Y9pTNzKE

**Comment by amandatsalis** [comment]
and how to use : server --join /ip4/127.0.0.1/tcp/10001/p2p/16Uiu2HAmJxxH1tScDX2rLGSU9exnuvZKNM9SoK3v315azp68DLPW

can i change or add new validator with costume address? not black hole address ?

**Comment by JekaMas** [comment]
I believe we need start/stop tests with `race` flag as well

**Comment by amandatsalis** [comment]
> race

how to use sir ?

**Comment by laviniat1996** [comment]
Hi @amandatsalis ,

Did this happen randomly or was there any action made before? Do you have the steps to reproduce it?

**Comment by amandatsalis** [comment]
> Hi @amandatsalis ,
> 
> Did this happen randomly or was there any action made before? Do you have the steps to reproduce it?

is randomly im create 1 instance to deploy 5 node using docker compose,

**Comment by laviniat1996** [comment]
@amandatsalis Can you please provide the full logs?

**Comment by laviniat1996** [comment]
Also, how many txs did you send? The logs say that thetxpool has a lot of enqueued transactions. How did you send them?

**Comment by amandatsalis** [comment]
> Juga, berapa banyak tx yang Anda kirim? Log mengatakan bahwa thetxpool memiliki banyak transaksi yang antri. Bagaimana Anda mengirim mereka?

10k tx. I use bots for transaction testing.  and 5 node validator open port RPC Api, im not create node non-validator


logs docker node : 

root@validator:/mnt/volume_sgp1_01/docker# `docker logs -f XXXXXXXXX`

[SIGNAL] Caught signal: terminated
Gracefully shutting down client...
[SIGNAL] Caught signal: terminated
Gracefully shutting down client...
 
DEBUG : 
2022-11-09T13:14:57.429Z [INFO]  polygon.server.ibft: block committed: number=1098 hash=0x420a6f3a3792eddbbc67a5ffa4f2093efe99c69d30a3a7b1b2aa79004f958f24 validation_type=ecdsa validators=5 committed=4
2022-11-09T13:14:57.435Z [INFO]  polygon.server.ibft.consensus: sequence done: height=1098
2022-11-09T13:14:57.437Z [INFO]  polygon.server.ibft.consensus: sequence started: height=1099
2022-11-09T13:14:57.438Z [INFO]  polygon.server.ibft.consensus: round started: round=0
2022-11-09T13:14:57.559Z [INFO]  polygon.blockchain: block already inserted: block=1098 source=syncer
2022-11-09T13:15:09.837Z [INFO]  polygon.blockchain: new block: number=1099 txs=70 hash=0xeb62277fd1cdb4beb9fef5f4396c713dda2cea797023126b5166b1ede65d4e1c parent=0x420a6f3a3792eddbbc67a5ffa4f2093efe99c69d30a3a7b1b2aa79004f958f24 generation_time_in_seconds=13
2022-11-09T13:15:09.841Z [INFO]  polygon.server.ibft: block committed: number=1099 hash=0xeb62277fd1cdb4beb9fef5f4396c713dda2cea797023126b5166b1ede65d4e1c validation_type=ecdsa validators=5 committed=4
2022-11-09T13:15:09.847Z [INFO]  polygon.server.ibft.consensus: sequence done: height=1099
2022-11-09T13:15:09.847Z [INFO]  polygon.server.ibft.consensus: sequence started: height=1100
2022-11-09T13:15:09.847Z [INFO]  polygon.server.ibft.consensus: round started: round=0
2022-11-09T13:15:09.927Z [INFO]  polygon.blockchain: block already inserted: block=1099 source=syncer
2022-11-09T13:15:15.533Z [ERROR] polygon.txpool: failed to add tx: err="already known"
2022-11-09T13:15:15.533Z [ERROR] polygon.server.dispatcher: failed to dispatch: method=eth_sendRawTransaction err="already known"
2022-11-09T13:15:15.601Z [ERROR] polygon.txpool: failed to add tx: err="already known"

**Comment by Kourin1996** [comment]
@amandatsalis Hello, this issue may have been fixed in this PR https://github.com/0xPolygon/polygon-edge/pull/839, which is not included in the latest release.

**Comment by Kourin1996** [comment]
Fixed in this PR https://github.com/0xPolygon/polygon-edge/pull/839 whose change has not been released yet

**Comment by laviniat1996** [comment]
Hi @amandatsalis ,

I will close this issue, as it was fixed in the PR mentioned above. But please feel free to reach out whenever an issue pops up.
