### ISSUE TITLE
Node 1 stopped, and all other 9 nodes stopped block production

### ISSUE THREAD

**Issue by ghost** [0xPolygon/polygon-edge#903]
# [ Subject of the issue ]
## Description
Describe your issue in as much detail as possible here.
Good evening. I have just got back to my office to find that Node 1 stopped with a block sync error, and all other 9 nodes stopped block production. 
## Your environment
- OS and version. Ubuntu 20.04
- The version of the Polygon Edge.    
  (*Confirm the version of your Polygon edge client by running the following command: `polygon-edge version --grpc-address GRPC_ADDRESS`*)
- The branch that causes this issue.
- Locally or Cloud hosted (which provider). Cloud AWS
- Please confirm if the validators are running under containerized environment (K8s, Docker, etc.). tmux

## Steps to reproduce
- Tell us how to reproduce this issue.
- Where the issue is, if you know.
- Which commands triggered the issue, if any.
- Provide us with the content of your genesis file.
- Provide us with commands that you used to start your validators.
- Provide us with the peer list of each of your validators by running the following command: `polygon-edge peers list --grpc-address GRPC_ADDRESS`.
- Is the chain producing blocks and serving customers atm? it was, but not now

## Expected behavior
- Tell us what should happen. make blocks on any nodes, even when just node 1 is down
- Tell us what happened instead. error at block 127308. unable to resync. deleted node1 folder. Resync stopped at block 40,000 ish. Now carried out a fresh install. Will restake to POS network.

## Logs
Provide us with debug logs from all of your validators by setting logging to `debug` output with: `server --log-level debug`

## Proposed solution
If you have an idea on how to fix this issue, please write it down here, so we can begin discussing it

**Comment by laviniat1996** [comment]
@Nexsuperne101 can you please provide the logs?

**Comment by ghost** [comment]
I am just about to redeploy all 10 nodes on a new genesis script, start as PoA, premine, issue the coins, send 5 million plus gas to each bootnode, stake, then flip it to PoS. The added nodes seem to end up as non-validators, even when the stake is set, and the BLS registered. It only affects the added, not those originally in the genesis script.

**Comment by laviniat1996** [comment]
@laviniat1996 I cannot advise you regarding this unless I see the logs. Otherwise, I have no way to know what is going on.

**Comment by Nexsuperne101** [comment]
Generating typings for: 3 artifacts in dir: types for target: ethers-v5
Successfully generated 7 typings!
Successfully generated 3 typings for external artifacts!
Solidity compilation finished successfully
Stake: address=0x0000000000000000000000000000000000001001, account=0xA9fBcb5aD371F14944Eb7Bb691D15074387710E2
Account balance: 30000000000000600600000000
ProviderError: not enough gas supplied for intrinsic gas costs
    at HttpProvider.request (/home/shazza/polygon-edge/staking-contracts/node_modules/hardhat/src/internal/core/providers/http.ts:49:19)
    at LocalAccountsProvider.request (/home/shazza/polygon-edge/staking-contracts/node_modules/hardhat/src/internal/core/providers/accounts.ts:187:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async EthersProviderWrapper.send (/home/shazza/polygon-edge/staking-contracts/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
shazza@poochainshazza:~/polygon-edge/staking-contracts$

**Comment by laviniat1996** [comment]
@Nexsuperne101  Do you have any tokens (coins) on the account from which you want to stake?

**Comment by ghost** [comment]
Generating typings for: 3 artifacts in dir: types for target: ethers-v5
Successfully generated 7 typings!
Successfully generated 3 typings for external artifacts!
Solidity compilation finished successfully
Stake: address=0x0000000000000000000000000000000000001001, account=0xA9fBcb5aD371F14944Eb7Bb691D15074387710E2
Account balance: 30000000000000600600000000
ProviderError: not enough gas supplied for intrinsic gas costs
    at HttpProvider.request (/home/shazza/polygon-edge/staking-contracts/node_modules/hardhat/src/internal/core/providers/http.ts:49:19)
    at LocalAccountsProvider.request (/home/shazza/polygon-edge/staking-contracts/node_modules/hardhat/src/internal/core/providers/accounts.ts:187:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async EthersProviderWrapper.send (/home/shazza/polygon-edge/staking-contracts/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)

**Comment by ghost** [comment]
I sent 30 million to each, but I get the above error. Does the staking wallet need a few coins as well?

**Comment by ghost** [comment]
5 million to stake, as set in stake.ts We premined 1 billion successfully, and sent 30 million to all 10 boot nodes. block creation is running

**Comment by laviniat1996** [comment]
@Nexsuperne101 So, you created a PoA network with 10 nodes, right? Did you use the flag `--ibft-validator` or `--ibft-validators-prefix-path` when generating the genesis file? Also, are you trying to stake from one of those nodes' address?

**Comment by ghost** [comment]
I was trying to stake from any of the 10. I used the ift-validator flags for all 10

**Comment by ghost** [comment]
I think I pinned it down . I used the max validators flag in the genesis script. I set it to 150, but on npm run info, it stated mx validators =0. Minimum =0 I have now deleted that flag, and will try again.

**Comment by laviniat1996** [comment]
@Nexsuperne101 If you start with PoA mode and want to switch to PoS, follow this guide : https://wiki.polygon.technology/docs/edge/consensus/migration-to-pos . Create the switch and then stake the funds between `deployment` and `from`.

**Comment by laviniat1996** [comment]
@Nexsuperne101 Also, do you recall what error did you get when the block production stopped?

**Comment by ghost** [comment]
It was a block sync invalid signature error. I have it up and running now. 10 validators, all staked, all bls registered. Is it normal that not all of them say "syncer" of the 7 nodes I can see, 6 say syncer, 1 does not. All are correct in the boot node ID section of the genesis.json of all 10 nodes. I have checked with npm run info to confirm they are all staked validators.

**Comment by laviniat1996** [comment]
@Nexsuperne101 Did you set an `epoch-size`?

**Comment by ghost** [comment]
No, I didn't. I changed it with sudo nano genesis.json on all 10 nodes. I
did find the epoch size caused exactly this error when I reinstalled it,
and then went to sync a new node. Sometimes the error language is a bit
confusing for me, but the staking was done, PoS migration was successful on
all the other nodes, so epoch value was the only other thing I changed that
it could have been.

I take it I can specify epoch in the genesis deployment script?

Thanks for your help,
Nex

**Comment by laviniat1996** [comment]
@Nexsuperne101 Did you manage to stake from all validators between `deployment` and `from` when you made the switch? If you didn't, then the stakers added after the from block will be added when the new epoch is hit. The epoch-size by default is `100000` blocks. You can change this when you create the genesis file, by using the genesis flag : 
`genesis [--epoch-size EPOCH_SIZE]`
example: `genesis --epoch-size 50`

**Comment by ghost** [comment]
I managed to get 9 out 10 done, but node 2 needed a resync, so that was
successfully re-added later. Epoch is set to 50. I watched it go from
non-validator to validator as the next epoch started. I think I have it
running as intended. Only one node doesn't show "syncer", all the others
do. All nodes show "we are the proposer".

**Comment by laviniat1996** [comment]
@Nexsuperne101 Can you recall if you did something different on that node? You can run` npm run info` and see if it is on the staking list.

**Comment by laviniat1996** [comment]
@Nexsuperne101 If all the nodes show `block committed` and `we are the proposer` means that they are validators.

**Comment by ghost** [comment]
I ran npm run info, and all nodes and BLS keys for the 10 are registered.
Why do some say syncer, and this particular one does not? Is it anything to
worry about? I'm just trying to make sure we are ready for the next step.

Thanks
Nex

**Comment by laviniat1996** [comment]
@Nexsuperne101 can you please post the logs from that node?

**Comment by ghost** [comment]
2022-11-15T14:01:40.672Z [INFO]  polygon.server.ibft.consensus: sequence started: height=95871
2022-11-15T14:01:40.672Z [INFO]  polygon.server.ibft.consensus: round started: round=0
2022-11-15T14:01:43.057Z [INFO]  polygon.blockchain: new block: number=95871 txs=0 hash=0x95bcec5290da66e22c69940628ff5290afb391d26a9eea1cacfd9d1665178cfe parent=0xc3815cbeee98d2fc137e537b6c9d00bd7893b6f8afb9bca7cdb6daaac2712567 generation_time_in_seconds=2
2022-11-15T14:01:43.057Z [INFO]  polygon.server.ibft: block committed: number=95871 hash=0x95bcec5290da66e22c69940628ff5290afb391d26a9eea1cacfd9d1665178cfe validation_type=bls validators=10 committed=7
2022-11-15T14:01:43.057Z [INFO]  polygon.server.ibft.consensus: sequence done: height=95871
2022-11-15T14:01:43.057Z [INFO]  polygon.server.ibft.consensus: sequence started: height=95872
2022-11-15T14:01:43.057Z [INFO]  polygon.server.ibft.consensus: round started: round=0
2022-11-15T14:01:45.343Z [INFO]  polygon.blockchain: new block: number=95872 txs=0 hash=0x59af5ce12c7fd85f600148d4a91e5dfe195278e6ec74586d631318c5cead65c6 parent=0x95bcec5290da66e22c69940628ff5290afb391d26a9eea1cacfd9d1665178cfe generation_time_in_seconds=3
2022-11-15T14:01:45.343Z [INFO]  polygon.server.ibft: block committed: number=95872 hash=0x59af5ce12c7fd85f600148d4a91e5dfe195278e6ec74586d631318c5cead65c6 validation_type=bls validators=10 committed=7
2022-11-15T14:01:45.343Z [INFO]  polygon.server.ibft.consensus: sequence done: height=95872
2022-11-15T14:01:45.343Z [INFO]  polygon.server.ibft.consensus: sequence started: height=95873
2022-11-15T14:01:45.343Z [INFO]  polygon.server.ibft.consensus: round started: round=0
2022-11-15T14:01:47.705Z [INFO]  polygon.blockchain: new block: number=95873 txs=0 hash=0x34ac975fbf1494b9aebaf256aa5855de3f2cab5a76135d122cb2ff534f13b431 parent=0x59af5ce12c7fd85f600148d4a91e5dfe195278e6ec74586d631318c5cead65c6 generation_time_in_seconds=2
2022-11-15T14:01:47.705Z [INFO]  polygon.server.ibft: block committed: number=95873 hash=0x34ac975fbf1494b9aebaf256aa5855de3f2cab5a76135d122cb2ff534f13b431 validation_type=bls validators=10 committed=7
2022-11-15T14:01:47.705Z [INFO]  polygon.server.ibft.consensus: sequence done: height=95873
2022-11-15T14:01:47.705Z [INFO]  polygon.server.ibft.consensus: sequence started: height=95874
2022-11-15T14:01:47.705Z [INFO]  polygon.server.ibft.consensus: round started: round=0
2022-11-15T14:01:50.036Z [INFO]  polygon.blockchain: new block: number=95874 txs=0 hash=0xf5b7c5ba339ae407ab08ce26911ae15966c14744ce517301e20e87c20dbfed2d parent=0x34ac975fbf1494b9aebaf256aa5855de3f2cab5a76135d122cb2ff534f13b431 generation_time_in_seconds=2
2022-11-15T14:01:50.036Z [INFO]  polygon.server.ibft: block committed: number=95874 hash=0xf5b7c5ba339ae407ab08ce26911ae15966c14744ce517301e20e87c20dbfed2d validation_type=bls validators=10 committed=7
2022-11-15T14:01:50.036Z [INFO]  polygon.server.ibft.consensus: sequence done: height=95874
2022-11-15T14:01:50.036Z [INFO]  polygon.server.ibft.consensus: sequence started: height=95875
2022-11-15T14:01:50.036Z [INFO]  polygon.server.ibft.consensus: round started: round=0
2022-11-15T14:01:50.036Z [INFO]  polygon.server.ibft.consensus: we are the proposer
2022-11-15T14:01:52.037Z [INFO]  polygon.server.ibft: executed txs: successful=0 failed=0 skipped=0 remaining=0
2022-11-15T14:01:52.038Z [INFO]  polygon.server.ibft: build block: number=95875 txs=0
2022-11-15T14:01:52.355Z [INFO]  polygon.blockchain: new block: number=95875 txs=0 hash=0xd13567cd018725964851a40c6a22245c6f74c8b5b41e7f9eb5bf0b4c1974cc9b parent=0xf5b7c5ba339ae407ab08ce26911ae15966c14744ce517301e20e87c20dbfed2d generation_time_in_seconds=3
2022-11-15T14:01:52.355Z [INFO]  polygon.server.ibft: block committed: number=95875 hash=0xd13567cd018725964851a40c6a22245c6f74c8b5b41e7f9eb5bf0b4c1974cc9b validation_type=bls validators=10 committed=7
2022-11-15T14:01:52.355Z [INFO]  polygon.server.ibft.consensus: sequence done: height=95875
2022-11-15T14:01:52.355Z [INFO]  polygon.server.ibft.consensus: sequence started: height=95876
2022-11-15T14:01:52.355Z [INFO]  polygon.server.ibft.consensus: round started: round=0
 That said. It says Source=syncer every once in a while now. Yesterday it wasn't

**Comment by laviniat1996** [comment]
@Nexsuperne101 If you are refering to this message  `block already inserted: block=300 source=syncer`, then you don't have to worry about it. It just means that the block was already added by another validator, so it jumps to the next block.

Regarding your logs, they look perfectly fine and your validator is working as it is supposed to 👍

**Comment by laviniat1996** [comment]
@Nexsuperne101 I will close this issue now, as your chain runs okay. Please feel free to reach out whenever there is an issue. 🙏

**Comment by ghost** [comment]
Thank you for your help, it's much appreciated.
